name: Trigger Automation Tests

on:
  push:
    branches:
      - main   # change if your main branch has another name

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/shadab012s/practice-testing-automation/dispatches \
          -d '{"event_type":"run-tests"}'
